In [2]:
import numpy as np

In [3]:
#insert
arr=np.array([10,20,30,40,50])
new_arr=np.insert(arr,2,99)
print(new_arr)


[10 20 99 30 40 50]
[10 20 30 40 50]


In [4]:
#2d array
arr2d=np.array([[1,2,3],
                [4,5,6]])
#insert a new column
new_col=np.insert(arr2d,1,[99,100],axis=1)
print(new_col)

[[  1  99   2   3]
 [  4 100   5   6]]


In [8]:
#insert a row
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_row=np.insert(arr2d,1,[7,8,9],axis=0)
print(new_row)


[[1 2 3]
 [7 8 9]
 [4 5 6]]


## Append

In [6]:
arr=np.array([1,2,3])
new_arr=np.append(arr,[4,5])
print(new_arr)

[1 2 3 4 5]


In [16]:
arr2d=np.array([[1,2],
                [3,4]])
new_row=np.append(arr2d,[[5,6]],axis=0)
print(new_row)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
arr2d=np.array([[1,2],
                [3,4]])
new_col=np.append(arr2d ,[[5],[6]],axis=1)
print(new_col)

[[1 2 5]
 [3 4 6]]


## delete

In [19]:
arr=np.array([1,2,3,4,5])
new_arr=np.delete(arr,2)
print(new_arr)

[1 2 4 5]


In [21]:
#delete a 2nd row
arr2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
new_row=np.delete(arr2d,1,axis=0)
print(new_row)

[[1 2 3]
 [7 8 9]]


In [22]:
#delete a 2nd coloum
arr2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
new_row=np.delete(arr2d,1,axis=1)
print(new_row)


[[1 3]
 [4 6]
 [7 9]]


## ARRAY SHAPE MANIPULATION

## RESHAPE()

In [25]:
#1d array
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print("original\n",arr)
print('------------------')
print("reshaped\n",reshaped)

original
 [1 2 3 4 5 6]
------------------
reshaped
 [[1 2 3]
 [4 5 6]]


In [26]:
#2d array
arr=np.array([[1,2],
              [2,3],
              [4,5]])
print(np.reshape(arr,(2,3)))

[[1 2 2]
 [3 4 5]]


## FLATTEN

In [29]:
arr=np.array([[1,2],
              [2,3],
              [4,5]])
V=arr.flatten()
print("Original:\n",arr)
print("-------------")
print("flatten array:",V)

Original:
 [[1 2]
 [2 3]
 [4 5]]
-------------
flatten array: [1 2 2 3 4 5]


## ravel()

In [31]:
arr=np.array([[1,2],
              [2,3],
              [4,5]])
V=arr.ravel()
print("Original:\n",arr)
print("-------------")
print("ravel array:",V)

Original:
 [[1 2]
 [2 3]
 [4 5]]
-------------
ravel array: [1 2 2 3 4 5]


In [33]:
arr=np.array([[1,2],
              [2,3],
              [4,5]])
V=arr.flatten()
V[0]=100                              #DOES,NT AFFECT IN ORIGINAL ARRAY
print("Original:\n",arr)
print("-------------")
print("flatten array:",V)

Original:
 [[1 2]
 [2 3]
 [4 5]]
-------------
flatten array: [100   2   2   3   4   5]


In [34]:
arr=np.array([[1,2],
              [2,3],
              [4,5]])
V=arr.ravel()
V[0]=100                                       #AFFECT IN THE ORIGINAL ARRAY
print("Original:\n",arr)
print("-------------")
print("ravel array:",V)

Original:
 [[100   2]
 [  2   3]
 [  4   5]]
-------------
ravel array: [100   2   2   3   4   5]


In [ ]:
#view()--->if new array modifies ,then that modification affects\not the original array
#changes made in flatten array will not affect the original array
#changes made in the revel array will affecr the original array

## transpose

In [37]:
arr=np.array([[1,2,3],[4,5,6]])
t=arr.transpose()

print("original \n",arr)
print("transpose\n",t)

original 
 [[1 2 3]
 [4 5 6]]
transpose
 [[1 4]
 [2 5]
 [3 6]]


In [38]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
reshaped=arr.reshape(3,4)
re=arr.reshape(4,3)
rav=arr.ravel()
fla=arr.flatten()
t=arr.transpose()
print("reshaped 3*4 array\n",reshaped)
print("reshaped 4*3 array\n",re)
print("ravel array\n",rav)
print("flatten\n",fla)
print("transpose\n",t)

reshaped 3*4 array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshaped 4*3 array
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ravel array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
flatten
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
transpose
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


## ITERATING OVER 1D AND 2D NUMPY ARRAY

In [39]:
#1d array
arr1=np.array([1,2,3,4,5,6])
for i in arr1:
    print(i)

1
2
3
4
5
6


In [40]:
#np.nditer()
arr1=np.array([1,2,3,4,5,6])
for i in np.nditer(arr1):
    print(i)



1
2
3
4
5
6


In [45]:
#2d array
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
#row by row
for i in arr2d:
    print(i)
print('-------------')
#element wise
for i in arr2d:
    for j in i:
        print(j, end=" ")
    print()

[1 2 3]
[4 5 6]
[7 8 9]
-------------
1 2 3 
4 5 6 
7 8 9 


In [46]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in np.nditer(arr2d):
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

## operators

## arthematic 

In [47]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print("Addition", a+b)
print("substraction",a-b)
print("multiplication",a*b)
print("Division",a/b)
print("Floor division",a//b)
print("Exponent",a**b)

Addition [11 22 33]
substraction [ 9 18 27]
multiplication [10 40 90]
Division [10. 10. 10.]
Floor division [10 10 10]
Exponent [   10   400 27000]


## comparision

In [50]:
a=np.array([10,20,30])
b=np.array([20,20,25])
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

[False  True False]
[ True False  True]
[False False  True]
[ True False False]
[False  True  True]
[ True  True False]
