In [2]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4],
            [2,4,6,8],
            [10,20,30,40]])
b=np.array([2,4,6,8])
print(a)
print("-"*20)
print(a.shape)
print(b.shape)
print("-"*20)
print(a+b)
print("-"*20)
print(a-b)
print("-"*20)
print(a*b)
print("-"*20)
print(a/b)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [10 20 30 40]]
--------------------
(3, 4)
(4,)
--------------------
[[ 3  6  9 12]
 [ 4  8 12 16]
 [12 24 36 48]]
--------------------
[[-1 -2 -3 -4]
 [ 0  0  0  0]
 [ 8 16 24 32]]
--------------------
[[  2   8  18  32]
 [  4  16  36  64]
 [ 20  80 180 320]]
--------------------
[[0.5 0.5 0.5 0.5]
 [1.  1.  1.  1. ]
 [5.  5.  5.  5. ]]


In [3]:
arr1=np.arange(15).reshape(5,3)
print(arr1)
arr2=np.arange(5).reshape(5,1)
print(arr2)
print(arr1+arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [5]:
a=np.array([[1,2,3,4],
            [2,4,6,8],
            [10,20,30,40]])
print(a)
b=a.T
print(b)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [10 20 30 40]]
[[ 1  2 10]
 [ 2  4 20]
 [ 3  6 30]
 [ 4  8 40]]


In [7]:
a=np.array(['a','b','g'])
print(a.dtype)

<U1


In [8]:
a=np.array([['welcome'],['hi']])
print(a)

[['welcome']
 ['hi']]


In [9]:
print(np.char.add(['welcome'],['hi']))

['welcomehi']


In [10]:
a=np.array(['hello',' '])
b=np.array(['world','numpy'])
result=np.char.add(a,b)
print(result)

['helloworld' ' numpy']


## Rounding Functions

## 1.round()

In [11]:
arr=np.array([3.2,3.6,7.89])
print(np.round(arr))

[3. 4. 8.]


## 2.floor()

In [12]:
arr1=np.array([3.9,2.5,-1.2,7.7])
print(np.floor(arr1))

[ 3.  2. -2.  7.]


## 3.ceil()

In [13]:
arr=np.array([3.1,2.8,-1.2,4.5])
print(np.ceil(arr))

[ 4.  3. -1.  5.]


# where()

In [15]:
a=np.array([40,50,70,20,85])
print(np.where(a>50,'pass','fail')) #if else logic 
print(np.where(a>50))  #it will give index positions

['fail' 'fail' 'pass' 'fail' 'pass']
(array([2, 4]),)


# np.any()

In [17]:
arr=np.array([0,0,5,0])
print(np.any(arr))
arr1=np.array([0,0])
print(np.any(arr1))

a2d=np.array([[1,0],[0,0]])
print(np.any(a2d))

True
False
True
