## logical operator

In [2]:
#logical operator
import numpy as np
a=np.array([10,20,30,40])
print(np.logical_and(a>15,a>35))
print(np.logical_or(a>15,a>35))
print(np.logical_not(a>25))

[False False False  True]
[False  True  True  True]
[ True  True False False]


## assignment operator

In [3]:
#assignment operator
a=np.array([10,20,30])
a=a+5
print(a)
a-=5
print(a)
a*=2
print(a)
a//=2
print(a)
a%=4
print(a)
a**=2
print(a)


[15 25 35]
[10 20 30]
[20 40 60]
[10 20 30]
[2 0 2]
[4 0 4]


## numpy maths

In [4]:
#square root
import math
numbers=[4,9,16,25]
b=[math.sqrt(i) for i in numbers]
print(b)

[2.0, 3.0, 4.0, 5.0]


In [5]:
arr=np.array([4,9,16,25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [6]:
arr2d=np.array([[4,9],[16,25]])
print(np.sqrt(arr2d))

[[2. 3.]
 [4. 5.]]


## exp()

In [7]:
print(math.exp(1))
print(math.exp(2))

2.718281828459045
7.38905609893065


In [8]:
arr=np.array([1,2,3])
result=np.exp(arr)
print(result)


[ 2.71828183  7.3890561  20.08553692]


In [9]:
arr2d=np.array([[1,2],[4,5]])
result=np.exp(arr2d)
print(result)

[[  2.71828183   7.3890561 ]
 [ 54.59815003 148.4131591 ]]


## sin cos

In [10]:
angle_deg=np.array([0,30,45,90])
#convert degrees to radians
angle_rad=np.deg2rad(angle_deg)
print("radians\n",angle_rad)
#sin values
sinval=np.sin(angle_rad)
print("sin values:",sinval)

radians
 [0.         0.52359878 0.78539816 1.57079633]
sin values: [0.         0.5        0.70710678 1.        ]


In [11]:
arr2d=np.array([[0,30],[45,90]])
angle_rad=np.deg2rad(arr2d)
print("radians\n",angle_rad)
#sin values
sinval=np.sin(angle_rad)
print("sin values:\n",sinval)
cosval=np.cos(angle_rad)
print("cos values:\n",cosval)

radians
 [[0.         0.52359878]
 [0.78539816 1.57079633]]
sin values:
 [[0.         0.5       ]
 [0.70710678 1.        ]]
cos values:
 [[1.00000000e+00 8.66025404e-01]
 [7.07106781e-01 6.12323400e-17]]


In [12]:
angles=np.array([0,np.pi/4,np.pi/3,np.pi/2])
cos_values=np.cos(angles)
print("angles(radians):",angles)
print("cosine values:",cos_values)

angles(radians): [0.         0.78539816 1.04719755 1.57079633]
cosine values: [1.00000000e+00 7.07106781e-01 5.00000000e-01 6.12323400e-17]


## add()

In [13]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(np.add(a,b))

[6 6 9]


In [14]:
arr2d=np.array([[1,3],[4,9]])
arr2d1=np.array([[11,2],[5,8]])
print(np.add(arr2d,arr2d1))

[[12  5]
 [ 9 17]]


## subtract()

In [15]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(np.subtract(b,a))


[4 2 3]


# multiply()

In [16]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(np.multiply(a,b))

[ 5  8 18]


In [17]:
arr2d=np.array([[1,3],[4,9]])
arr2d1=np.array([[11,2],[5,8]])
print(np.multiply(arr2d,arr2d1))

[[11  6]
 [20 72]]


# divide()

In [18]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(np.divide(a,b))

[0.2 0.5 0.5]


In [19]:
arr2d=np.array([[1,3],[4,9]])
arr2d1=np.array([[11,2],[5,8]])
print(np.divide(arr2d,arr2d1))

[[0.09090909 1.5       ]
 [0.8        1.125     ]]


# dot()

In [20]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(np.dot(a,b))

31


In [21]:
rr2d=np.array([[1,3],[4,9]])
arr2d1=np.array([[11,2],[5,8]])
print(np.dot(arr2d,arr2d1))

[[26 26]
 [89 80]]


# @operator

In [22]:
a=np.array([1,2,3])   #same like dot product
b=np.array([5,4,6])
c=a@b
print(c)

31


In [23]:
arr2d=np.array([[1,3],[4,9]])
arr2d1=np.array([[11,2],[5,8]])
c=arr2d@arr2d1
print(c)

[[26 26]
 [89 80]]


# numpy statistics

# sum()

In [24]:
a=np.array([1,2,3,4])
print(np.sum(a))

10


In [25]:
a=np.array([[1,3],[4,9]])
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

[ 4 13]
[ 5 12]


# min()

In [26]:
a=np.array([1,2,3,4])
print(np.min(a))

1


In [27]:
a=np.array([[1,3],[4,9]])
print(np.min(a))
print(np.min(a,axis=1))
print(np.min(a,axis=0))


1
[1 4]
[1 3]


# max()

In [28]:
a=np.array([1,2,3,4])
print(np.max(a))

4


In [29]:
a=np.array([[1,3],[4,9]])
print(np.max(a))
print(np.max(a,axis=1))
print(np.max(a,axis=0))


9
[3 9]
[4 9]


# mean()

In [30]:
arr=np.array([50,70,90,60])
avr=np.mean(arr)
print(avr)

67.5


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
avrg=np.mean(arr)
print(avrg)

3.5


In [34]:
#for column and row
arr=np.array([[1,2,3],[4,5,6]])
avrg=np.mean(arr ,axis=0)
print(avrg)
a=np.mean(arr,axis=1)
print(a)

[2.5 3.5 4.5]
[2. 5.]


# median

In [35]:
arr=np.array([50,70,90,60])
med=np.median(arr)
print(med)

65.0


In [36]:
arr=np.array([[1,2,3],[4,5,6]])
med=np.median(arr)
print(med)

3.5


# variance

In [3]:
marks=np.array([50,30,70,90,60])
v=np.var(marks)
print(v)


400.0


In [5]:
arr=np.array([[1,2,3],[4,5,6]])
m=np.var(arr)
print(m)
e=np.var(arr,axis=0) #column
d=np.var(arr,axis=1)
print(e,d)

2.9166666666666665
[2.25 2.25 2.25] [0.66666667 0.66666667]


# standard deviation

In [6]:
marks=np.array([50,30,70,90,60])
v=np.std(marks)
print(v)


20.0


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
m=np.std(arr)
print(m)
e=np.std(arr,axis=0) #column
d=np.std(arr,axis=1)
print(e,d)

1.707825127659933
[1.5 1.5 1.5] [0.81649658 0.81649658]


# corelation cofficent

In [9]:
#positive
x=[1,2,3,4,5]
y=[2,4,6,8,10]
corr=np.corrcoef(x,y)
print(corr)
#negative
a=[1,2,3,4,5]
b=[10,8,6,4,2]
co=np.corrcoef(a,b)
print(co)

[[1. 1.]
 [1. 1.]]
[[ 1. -1.]
 [-1.  1.]]
