In [1]:
import numpy as np

# array manipulation

In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [6]:
a=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
b=np.concatenate((a,c))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
a=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
b=np.concatenate((a,c),axis=0) #row wise

d=np.concatenate((a,c),axis=1) #column wise
print(b)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# vstack()


In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
v=np.vstack((a,b))
print(v)

[[1 2 3]
 [4 5 6]]


In [10]:
#2d 
a=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
v=np.vstack((a,c))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# hstack()

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])
v=np.hstack((a,b))
print(v)

[1 2 3 4 5 6]


In [12]:
#2d 
a=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
v=np.vstack((a,c))
print(v)

[[1 2 5 6]
 [3 4 7 8]]


# column stack

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
v=np.column_stack((a,b))
print(v)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
#2d 
a=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
v=np.column_stack((a,c))
print(v)

[[1 2 5 6]
 [3 4 7 8]]


# split
# 1.hsplit()

In [21]:
a=np.array([[1,2,3,8],[4,5,6,9]])

v=np.hsplit(a,2)
print(v)

[array([[1, 2],
       [4, 5]]), array([[3, 8],
       [6, 9]])]


# 2.vsplit()

In [22]:
a=np.array([[1,2,3,8],[4,5,6,9],[11,12,13,14],[15,26,17,18]])
vs=np.vsplit(a,2)
print(vs)


[array([[1, 2, 3, 8],
       [4, 5, 6, 9]]), array([[11, 12, 13, 14],
       [15, 26, 17, 18]])]


In [23]:
v=np.vsplit(a,4)
print(v)

[array([[1, 2, 3, 8]]), array([[4, 5, 6, 9]]), array([[11, 12, 13, 14]]), array([[15, 26, 17, 18]])]


# sorting arrays

# sort()

In [24]:
#assending
arr=np.array([2,1,7,4])
sr=np.sort(arr)
print(arr)
print(sr)

[2 1 7 4]
[1 2 4 7]


In [25]:
#descending array
print(sr[::-1])

[7 4 2 1]


In [26]:
#2d
a=np.array([[1,2,3,8],[4,5,6,9]])
sr=np.sort(a)
print(sr)
print(sr[::-1])

[[1 2 3 8]
 [4 5 6 9]]
[[4 5 6 9]
 [1 2 3 8]]


# argsort()

In [27]:
arr=np.array([2,1,7,4])
ar=np.argsort(arr)
print(ar)

[1 0 3 2]


In [29]:
a=np.array([[1,2,10,8],[4,20,6,9]])
sr=np.argsort(a)
print(sr)

[[0 1 3 2]
 [0 2 3 1]]
