## astype()

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
arr_1=arr.astype(np.float32)

print(arr.dtype)
print(arr_1.dtype)

int64
float32


In [5]:
a=np.array([1,2,3,4])
print(a)
print(a.dtype)
b=np.array([1,2,3,4,'hello'])
print(b.dtype) #it will change to string to all elements

[1 2 3 4]
int64
<U21


## Random Numbers

In [7]:
#np.random.rand()   numbers b/w 0 and 1
print(np.random.rand())

#1d array of 5 random elements
print(np.random.rand(5))

#2d array (3rows 2coloumns)
print(np.random.rand(3,2))

np.random

0.8924008182495924
[0.72805407 0.57285536 0.50251712 0.93320344 0.29961883]
[[0.40362764 0.8863546 ]
 [0.405257   0.35403069]
 [0.07193115 0.956378  ]]


In [8]:
#np.random.randn()
print(np.random.randn())
print("----------------")
print(np.random.randn(5))
print("----------------")
print(np.random.randn(3,2))

-0.4577010288349037
----------------
[-0.54041045  0.81997715 -1.60969854 -1.53158303  1.37532471]
----------------
[[ 0.02570125  0.60819851]
 [ 2.00047896 -0.13783383]
 [ 0.23685533  1.62034893]]


In [11]:
# np.random.randint()
print(np.random.randint(1,10,size=5))  #1 to 9 ,no.of elements :5

#2d array
print(np.random.randint(1,10,size=(2,3)))

[6 1 1 5 3]
[[9 6 1]
 [5 3 2]]


In [12]:
#np.random.uniform(start ,stop)
print(np.random.uniform(1,10,size=5))  #1 to 9 ,no.of elements :5

#2d array
print(np.random.uniform(1,10,size=(2,3)))

[4.82955502 2.16880396 7.99203736 9.46596557 3.75600383]
[[7.45078463 4.98269601 4.33270699]
 [1.47892946 8.40000184 3.54850542]]


## indexing

In [16]:
arr=np.array([20,30,40])
print(arr)
print("----------------")
print(arr[0])
print(arr[1])
print(arr[2])
print("----------------")
print(arr[-1])
print(arr[-2])




[20 30 40]
----------------
20
30
40
----------------
40
30


In [17]:
# slicing :extract a portion (sub_array) form the array
#arr[start:stop:stepsize)
arr=np.array([20,30,40,50,60])
print(arr[0:4])
print(arr[0:5:2])
print(arr[::-1])


[20 30 40 50]
[20 40 60]
[60 50 40 30 20]


In [26]:
## 2d array
arr=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
print(arr)
print('----------------')
print(arr[0,0])
print(arr[2,2])
print(arr[2,1])
print('--------------')
print(arr[-2,-2])
print(arr[-3,-3])
print(arr[-1,-1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------
10
90
80
--------------
50
10
90


In [43]:
arr=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
print(arr[0,:]) #extract the first row
print(arr[1,:])
print(arr[2,:])
print('------------------')
print(arr[:,0]) #extract the colomn
print(arr[:,1])
print(arr[:,2])
print('-----------------')
print(arr[0:2,:])
print(arr[0:2,0:2])
print("----------------")
print(arr[1:3,:])
print("---------------")
print(arr[:,1:3])

[10 20 30]
[40 50 60]
[70 80 90]
------------------
[10 40 70]
[20 50 80]
[30 60 90]
-----------------
[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]]
----------------
[[40 50 60]
 [70 80 90]]
---------------
[[20 30]
 [50 60]
 [80 90]]


## boolean indexing

In [44]:
arr=np.array([1,2,3,4,5])
cond=arr>3
print(cond)
print(arr[cond])

[False False False  True  True]
[4 5]


In [45]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

[4 5]


In [47]:
arr2d=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
print("Condition:\n",arr2d>50)
print(arr2d[arr2d>50])

Condition:
 [[False False False]
 [False False  True]
 [ True  True  True]]
[60 70 80 90]


## Updating numpy array

In [51]:
arr=np.array([10,20,30,40,50])
arr[0]=100
arr[1:3]=200,300
print(arr)
#fancy indexing
arr[[3,4]]=[400,500]
#update using boolean indexing
arr[arr>300]=999
print(arr)

[100 200 300  40  50]
[100 200 300 999 999]


In [67]:
#updating numpy 2d array
arr2d=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
#update singe element
arr2d[0,0]=100
print(arr2d)
print("-------------")
#update entrie row
arr2d[1]=[400,500,600]
print(arr2d)
print("------------")
#updating a portion
arr2d[0:2,0:2]=[[111,222],
                [333,444]]
print(arr2d)
print("----------")
arr2d[:,2]=[555,666,777]
print(arr2d)
print("------------")
#boolean
arr2d[arr2d>600]=999
print(arr2d)




[[100  20  30]
 [ 40  50  60]
 [ 70  80  90]]
-------------
[[100  20  30]
 [400 500 600]
 [ 70  80  90]]
------------
[[111 222  30]
 [333 444 600]
 [ 70  80  90]]
----------
[[111 222 555]
 [333 444 666]
 [ 70  80 777]]
------------
[[111 222 555]
 [333 444 999]
 [ 70  80 999]]


In [85]:
arr2d=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
arr2d[-2:,-2:]=[[500,600],
                [800,900]]
print(arr2d)
print("----------")
arr2d[-3:-1,-3:-1]=[[100,200],
                    [400,500]]
print(arr2d)

[[ 10  20  30]
 [ 40 500 600]
 [ 70 800 900]]
----------
[[100 200  30]
 [400 500 600]
 [ 70 800 900]]
