In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a=[1,2,3]
# print(a+5)
#DIFF B/W ARRAY AND LIST
#it cannot add 5 to each element ,because we cannot add one data type to another ,so it will give error
# but in numpy array we can add 5 to each and every element 


In [4]:
marks=np.array([10,20,30,40,50])
avg=np.mean(marks)
print(avg)

30.0


In [6]:
print(np.__version__)

2.1.3


In [10]:
a=np.array([1,2,3])
b=np.array([[1,2,3],
           [4,5,6]])
print(a)
print("-------------------------")
print(b)
3

[1 2 3]
-------------------------
[[1 2 3]
 [4 5 6]]


In [16]:
#1D 2D 3D arrays

#1d(vetor)
a=np.array([1,2,3])
print("Dimension:",a.ndim)
print("shape:",a.shape) #no.of elements in tuple of integers 
print(a.size) #number of elements
print("-------------------------")
#2D (matrix)
b=np.array([[1,2,3],
           [4,5,6]])
print("Dimension:",b.ndim)
print("shape:",b.shape)
print(b.size)
print("-------------------------")
#3D--->block ,row,column
#cube or tensor ---->three dimensional array
c=np.array([[[1,2],
             [3,4]],

            [[5,6],
             [7,8]]])
print(c)
print("Dimension:",c.ndim)
print("shape:",c.shape)
print(c.size)
           


Dimension: 1
shape: (3,)
3
-------------------------
Dimension: 2
shape: (2, 3)
6
-------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3
shape: (2, 2, 2)
8


## NUMPY BUILT IN FUNCTIONS

In [17]:
#np.zeros()-->creates an array filled with 0s
#np.ones()-->creates an array filled with 1s
#np.arrange()-->creates an array with a range of numbers
#np.linspace()-->creates an array with evenly spaced numbers
#np.full()-->creates an array with specific value
#np.eye()-->creates a squared identity matrix
#np.zeros()-->creates an digonal array from a list or extracts diagonal

In [32]:
#np.zeros()-->creates an array filled with 0s
print("Zeros:\n",np.zeros((2,3)))

#np.ones()-->creates an array filled with 1s
print("ones:\n",np.ones((2,3)))

#np.arange()-->creates an array with a range of numbers
np.arange(1,11)

#np.linspace()-->creates an array with evenly spaced numbers
print("ones:\n",np.linspace(0,1,5))  #from 0to 1 ,it will gwnwrate 5 numbers

#np.full()-->creates an array with specific value
print("Full:\n",np.full((2,3),9))

#np.eye()-->creates a squared identity matrix
print("Eye:\n",np.eye(2))

#np.zeros()-->creates an digonal array from a list or extracts diagonal
print("dignoal:\n",np.diag([1,2,3]))



Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
ones:
 [0.   0.25 0.5  0.75 1.  ]
Full:
 [[9 9 9]
 [9 9 9]]
Eye:
 [[1. 0.]
 [0. 1.]]
dignoal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


## dtypes

In [34]:
arr=np.array([-1,-2,-3],dtype=np.int32)
print(arr)
print(arr.dtype)

[-1 -2 -3]
int32


In [35]:
ar=np.array([1,2,3],dtype=np.uint32)
print(ar)
print(ar.dtype)

[1 2 3]
uint32


## float

In [36]:
arr=np.array([1.5,2.5,3.5],dtype=np.float64)
print(arr)
print(arr.dtype)


[1.5 2.5 3.5]
float64


## complex

In [37]:
#complex64 ,complex128
arr=np.array([1+2j,2+4j],dtype=np.complex64)
print(arr)
print(arr.dtype)

[1.+2.j 2.+4.j]
complex64


## boolean

In [40]:
#stores True/False
arr=np.array([True, False, True],dtype=bool)
print(arr)
print(arr.dtype)

[ True False  True]
bool


## String/Unicode

In [41]:
#stores text values
#dtype="u1"-->unicode string per element
arr=np.array(['a','b','c'],dtype="U1")
print(arr)
print(arr.dtype)

['a' 'b' 'c']
<U1
